from __future__ import annotations
import csv
from io import BytesIO, StringIO
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from app.models import InvoiceData

def value(field): return field.value if hasattr(field,'value') else field or ''
def csv_export(data: InvoiceData) -> bytes:
 out=StringIO(newline=''); fields=['Invoice Number','Invoice Date','Supplier','Supplier GSTIN','Customer','Customer GSTIN','Item','SKU','HSN','Quantity','Unit','Rate','Discount','Taxable Value','GST','CGST','SGST','IGST','Total']
 writer=csv.DictWriter(out,fieldnames=fields,extrasaction='ignore');writer.writeheader()
 for item in data.items or [None]:
  row={'Invoice Number':value(data.invoice.get('number')),'Invoice Date':value(data.invoice.get('date')),'Supplier':value(data.supplier.name),'Supplier GSTIN':value(data.supplier.gstin),'Customer':value(data.customer.name),'Customer GSTIN':value(data.customer.gstin)}
  if item:
   row.update({'Item':value(item.product_name),'SKU':value(item.sku),'HSN':value(item.hsn),'Quantity':value(item.quantity),'Unit':value(item.unit),'Rate':value(item.rate),'Discount':value(item.discount),'Taxable Value':value(item.taxable_value),'GST':value(item.gst),'CGST':value(item.cgst),'SGST':value(item.sgst),'IGST':value(item.igst),'Total':value(item.line_total)})
  writer.writerow(row)
 return ('\ufeff'+out.getvalue()).encode('utf-8')
def excel_export(data: InvoiceData) -> bytes:
 wb=Workbook();ws=wb.active;ws.title='Invoice';ws.sheet_view.showGridLines=False
 widths=[6,32,12,10,12,14,14,14];
 for i,w in enumerate(widths,1):ws.column_dimensions[get_column_letter(i)].width=w
 navy='17324D'; thin=Side(style='thin',color='8FA3B8'); border=Border(left=thin,right=thin,top=thin,bottom=thin)
 ws.merge_cells('A1:E1');ws['A1']=value(data.supplier.name) or 'SUPPLIER';ws['A1'].font=Font(size=16,bold=True,color='FFFFFF');ws['A1'].fill=PatternFill('solid',fgColor=navy);ws['A1'].alignment=Alignment(vertical='center')
 ws.merge_cells('F1:H1');ws['F1']=data.layout.get('title','TAX INVOICE');ws['F1'].font=Font(size=14,bold=True,color='FFFFFF');ws['F1'].fill=PatternFill('solid',fgColor=navy);ws['F1'].alignment=Alignment(horizontal='right')
 ws.row_dimensions[1].height=30
 ws.merge_cells('A2:E3');ws['A2']=f"Address: {value(data.supplier.address)}\nGSTIN: {value(data.supplier.gstin)}";ws['A2'].alignment=Alignment(wrap_text=True,vertical='top')
 ws.merge_cells('F2:H2');ws['F2']=f"Invoice No: {value(data.invoice.get('number'))}";ws.merge_cells('F3:H3');ws['F3']=f"Date: {value(data.invoice.get('date'))}"
 ws.merge_cells('A5:H5');ws['A5']=f"Bill To: {value(data.customer.name)} | GSTIN: {value(data.customer.gstin)}";ws['A5'].font=Font(bold=True);ws['A5'].fill=PatternFill('solid',fgColor='E8F0F7')
 headers=['#','Item description','HSN/SAC','Qty','Unit','Rate','Taxable value','Line total'];
 for col,h in enumerate(headers,1):
  c=ws.cell(7,col,h);c.font=Font(bold=True,color='FFFFFF');c.fill=PatternFill('solid',fgColor=navy);c.border=border;c.alignment=Alignment(horizontal='center')
 for r,item in enumerate(data.items,8):
  vals=[value(item.serial_number),value(item.product_name),value(item.hsn),value(item.quantity),value(item.unit),value(item.rate),value(item.taxable_value),value(item.line_total)]
  for col,v in enumerate(vals,1):
   c=ws.cell(r,col,v);c.border=border;c.alignment=Alignment(vertical='top',wrap_text=col==2)
   if col in (6,7,8):c.number_format='₹#,##0.00'
  ws.row_dimensions[r].height=30
 end=8+len(data.items); ws.merge_cells(start_row=end,start_column=1,end_row=end,end_column=6);ws.cell(end,1,'Grand Total').font=Font(bold=True);ws.cell(end,1).alignment=Alignment(horizontal='right');total=ws.cell(end,7,value(data.totals.get('grand_total')));ws.merge_cells(start_row=end,start_column=7,end_row=end,end_column=8);total.font=Font(size=13,bold=True);total.number_format='₹#,##0.00'
 ws.merge_cells(start_row=end+2,start_column=1,end_row=end+2,end_column=8);ws.cell(end+2,1,'This editable reconstruction was generated by BillConvert.');ws.cell(end+2,1).font=Font(italic=True,color='5B6B7C')
 ws.print_area=f'A1:H{end+2}';ws.page_setup.orientation='portrait';ws.page_setup.fitToWidth=1;ws.sheet_properties.pageSetUpPr.fitToPage=True;ws.page_margins.left=.25;ws.page_margins.right=.25
 out=BytesIO();wb.save(out);return out.getvalue()
